### ISSUE TITLE
formgate.dev is down

### ISSUE THREAD

**Issue by xgpt** [formgate/formgate#2]
Is this project dead or just considered feature-complete?

**Comment by shivampaw** [comment]
It's up now :) If something came along we'd be happy to have a look

**Comment by xgpt** [comment]
Glad to see the site is back up. I always recommend that projects like these consider GitHub hosting, I’m not affiliated at all, but the Github Pages feature is free and doesn’t go down when you’re not looking (At least less often than self hosting)

Thank for the reply!
